src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=5000)
     */
    private $comment_content;

    /**
     * @ORM\Column(type="integer")
     */
    private $comment_author_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $comment_trick_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $comment_creation_date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="user_comments")
     * @ORM\JoinColumn(name="comment_author_id", referencedColumnName="id", nullable=false)
     */
    private $comment_author;

    /**
     * @ORM\ManyToOne(targetEntity=Trick::class, inversedBy="trick_comments")
     * @ORM\JoinColumn(name="comment_trick_id", referencedColumnName="id",nullable=false)
     */
    private $comment_trick;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentContent(): ?string
    {
        return $this->comment_content;
    }

    public function setCommentContent(string $comment_content): self
    {
        $this->comment_content = $comment_content;

        return $this;
    }

    public function getCommentAuthorId(): ?int
    {
        return $this->comment_author_id;
    }

    public function setCommentAuthorId(int $comment_author_id): self
    {
        $this->comment_author_id = $comment_author_id;

        return $this;
    }

    public function getCommentTrickId(): ?int
    {
        return $this->comment_trick_id;
    }

    public function setCommentTrickId(int $comment_trick_id): self
    {
        $this->comment_trick_id = $comment_trick_id;

        return $this;
    }

    public function getCommentCreationDate(): ?\DateTimeInterface
    {
        return $this->comment_creation_date;
    }

    public function setCommentCreationDate(\DateTimeInterface $comment_creation_date): self
    {
        $this->comment_creation_date = $comment_creation_date;

        return $this;
    }

    public function getCommentAuthor(): ?User
    {
        return $this->comment_author;
    }

    public function setCommentAuthor(?User $comment_author): self
    {
        $this->comment_author = $comment_author;

        return $this;
    }

    public function getCommentTrick(): ?Trick
    {
        return $this->comment_trick;
    }

    public function setCommentTrick(?Trick $comment_trick): self
    {
        $this->comment_trick = $comment_trick;

        return $this;
    }
}

src/Entity/Group.php
<?php

namespace App\Entity;

use App\Repository\GroupRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=GroupRepository::class)
 * @ORM\Table(name="`group`")
 */
class Group
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $group_name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $group_creation_date;

    /**
     * @ORM\OneToMany(targetEntity=Trick::class, mappedBy="trick_group")
     */
    private $group_tricks;

    public function __construct()
    {
        $this->group_tricks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGroupName(): ?string
    {
        return $this->group_name;
    }

    public function setGroupName(string $group_name): self
    {
        $this->group_name = $group_name;

        return $this;
    }

    public function getGroupCreationDate(): ?\DateTimeInterface
    {
        return $this->group_creation_date;
    }

    public function setGroupCreationDate(\DateTimeInterface $group_creation_date): self
    {
        $this->group_creation_date = $group_creation_date;

        return $this;
    }

    /**
     * @return Collection|Trick[]
     */
    public function getGroupTricks(): Collection
    {
        return $this->group_tricks;
    }

    public function addGroupTrick(Trick $groupTrick): self
    {
        if (!$this->group_tricks->contains($groupTrick)) {
            $this->group_tricks[] = $groupTrick;
            $groupTrick->setTrickGroup($this);
        }

        return $this;
    }

    public function removeGroupTrick(Trick $groupTrick): self
    {
        if ($this->group_tricks->removeElement($groupTrick)) {
            // set the owning side to null (unless already changed)
            if ($groupTrick->getTrickGroup() === $this) {
                $groupTrick->setTrickGroup(null);
            }
        }

        return $this;
    }
}

src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TrickRepository::class)
 * @UniqueEntity(fields="trick_name",message="Il existe déjà une figure avec un nom similaire.",groups={"trick_creation"})
 */
class Trick
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $trick_author_id;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $trick_name;

    /**
     * @ORM\Column(type="string", length=10000)
     */
    private $trick_description;

    /**
     * @ORM\Column(type="integer")
     */
    private $trick_group_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $trick_creation_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $trick_update_date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class,inversedBy="user_tricks")
     * @ORM\JoinColumn(name="trick_author_id", referencedColumnName="id", nullable=false)
     */
    private $trick_author;

    /**
     * @ORM\ManyToOne(targetEntity=Group::class, inversedBy="group_tricks")
     * @ORM\JoinColumn(name="trick_group_id", referencedColumnName="id",nullable=false)
     */
    private $trick_group;

    /**
     * @ORM\OneToMany(targetEntity=TrickAttachment::class, mappedBy="ta_trick")
     */
    private $trick_attachments;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="comment_trick")
     */
    private $trick_comments;


    private $trick_thumbnail = 'ff080.jpg';

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $trick_slug;

    public function __construct()
    {
        $this->trick_attachments = new ArrayCollection();
        $this->trick_comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTrickAuthorId(): ?int
    {
        return $this->trick_author_id;
    }

    public function setTrickAuthorId(int $trick_author_id): self
    {
        $this->trick_author_id = $trick_author_id;

        return $this;
    }

    public function getTrickName(): ?string
    {
        return $this->trick_name;
    }

    public function setTrickName(string $trick_name): self
    {
        $this->trick_name = $trick_name;

        return $this;
    }

    public function getTrickDescription(): ?string
    {
        return $this->trick_description;
    }

    public function setTrickDescription(string $trick_description): self
    {
        $this->trick_description = $trick_description;

        return $this;
    }

    public function getTrickGroupId(): ?int
    {
        return $this->trick_group_id;
    }

    public function setTrickGroupId(int $trick_group_id): self
    {
        $this->trick_group_id = $trick_group_id;

        return $this;
    }

    public function getTrickCreationDate(): ?\DateTimeInterface
    {
        return $this->trick_creation_date;
    }

    public function setTrickCreationDate(\DateTimeInterface $trick_creation_date): self
    {
        $this->trick_creation_date = $trick_creation_date;

        return $this;
    }

    public function getTrickUpdateDate(): ?\DateTimeInterface
    {
        return $this->trick_update_date;
    }

    public function setTrickUpdateDate(\DateTimeInterface $trick_update_date): self
    {
        $this->trick_update_date = $trick_update_date;

        return $this;
    }

    public function getTrickAuthor(): ?User
    {
        return $this->trick_author;
    }

    public function setTrickAuthor(?User $trick_author): self
    {
        $this->trick_author = $trick_author;

        return $this;
    }

    public function getTrickGroup(): ?Group
    {
        return $this->trick_group;
    }

    public function setTrickGroup(?Group $trick_group): self
    {
        $this->trick_group = $trick_group;

        return $this;
    }

    /**
     * @return Collection|TrickAttachment[]
     */
    public function getTrickAttachments(): Collection
    {
        return $this->trick_attachments;
    }

    public function addTrickAttachment(TrickAttachment $TrickAttachment): self
    {
        if (!$this->trick_attachments->contains($TrickAttachment)) {
            $this->trick_attachments[] = $TrickAttachment;
            $TrickAttachment->setTaTrick($this);
        }

        return $this;
    }

    public function removeTrickAttachment(TrickAttachment $TrickAttachment): self
    {
        if ($this->trick_attachments->removeElement($TrickAttachment)) {
            // set the owning side to null (unless already changed)
            if ($TrickAttachment->getTaTrick() === $this) {
                $TrickAttachment->setTaTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getTrickComments(): Collection
    {
        return $this->trick_comments;
    }

    public function addTrickComment(Comment $trickComment): self
    {
        if (!$this->trick_comments->contains($trickComment)) {
            $this->trick_comments[] = $trickComment;
            $trickComment->setCommentTrick($this);
        }

        return $this;
    }

    public function removeTrickComment(Comment $trickComment): self
    {
        if ($this->trick_comments->removeElement($trickComment)) {
            // set the owning side to null (unless already changed)
            if ($trickComment->getCommentTrick() === $this) {
                $trickComment->setCommentTrick(null);
            }
        }

        return $this;
    }

    public function getTrickThumbnail(): ?string
    {
        if (!is_null($first_image = $this->getFirstImage())) {
            $this->trick_thumbnail = $first_image->getTaFilename();
        }

        return $this->trick_thumbnail;
    }

    public function setTrickThumbnail(string $trick_thumbnail): self
    {
        $this->trick_thumbnail = $trick_thumbnail;

        return $this;
    }

    public function getTrickSlug(): ?string
    {
        return $this->trick_slug;
    }

    public function setTrickSlug(string $trick_slug): self
    {
        $this->trick_slug = $trick_slug;

        return $this;
    }

    public function getFirstImage()
    {
        $trick_attachments = $this->trick_attachments->toArray();

        foreach ($trick_attachments as $refernce) {
            if ($refernce->getTaType() === 'image') {
                return $refernce;
            }
        }

        return null;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_avatar;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $user_token;

    /**
     * @ORM\Column(type="boolean")
     */
    private $user_active;

    /**
     * @ORM\Column(type="boolean")
     */
    private $user_admin;

    /**
     * @ORM\Column(type="datetime")
     */
    private $user_registration_date;

    /**
     * @ORM\OneToMany(targetEntity=Trick::class, mappedBy="trick_author")
     */
    private $user_tricks;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="comment_author")
     */
    private $user_comments;

    public function __construct()
    {
        $this->user_tricks = new ArrayCollection();
        $this->user_comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserName(): ?string
    {
        return $this->user_name;
    }

    public function setUserName(string $user_name): self
    {
        $this->user_name = $user_name;

        return $this;
    }

    public function getUserEmail(): ?string
    {
        return $this->user_email;
    }

    public function setUserEmail(string $user_email): self
    {
        $this->user_email = $user_email;

        return $this;
    }

    public function getUserAvatar(): ?string
    {
        return $this->user_avatar;
    }

    public function setUserAvatar(string $user_avatar): self
    {
        $this->user_avatar = $user_avatar;

        return $this;
    }

    public function getUserPassword(): ?string
    {
        return $this->user_password;
    }

    public function setUserPassword(string $user_password): self
    {
        $this->user_password = $user_password;

        return $this;
    }

    public function getUserToken(): ?string
    {
        return $this->user_token;
    }

    public function setUserToken(string $user_token): self
    {
        $this->user_token = $user_token;

        return $this;
    }

    public function getUserActive(): ?bool
    {
        return $this->user_active;
    }

    public function setUserActive(bool $user_active): self
    {
        $this->user_active = $user_active;

        return $this;
    }

    public function getUserAdmin(): ?bool
    {
        return $this->user_admin;
    }

    public function setUserAdmin(bool $user_admin): self
    {
        $this->user_admin = $user_admin;

        return $this;
    }

    public function getUserRegistrationDate(): ?\DateTimeInterface
    {
        return $this->user_registration_date;
    }

    public function setUserRegistrationDate(\DateTimeInterface $user_registration_date): self
    {
        $this->user_registration_date = $user_registration_date;

        return $this;
    }

    /**
     * @return Collection|Trick[]
     */
    public function getUserTricks(): Collection
    {
        return $this->user_tricks;
    }

    public function addUserTrick(Trick $userTrick): self
    {
        if (!$this->user_tricks->contains($userTrick)) {
            $this->user_tricks[] = $userTrick;
            $userTrick->setTrickAuthor($this);
        }

        return $this;
    }

    public function removeUserTrick(Trick $userTrick): self
    {
        if ($this->user_tricks->removeElement($userTrick)) {
            // set the owning side to null (unless already changed)
            if ($userTrick->getTrickAuthor() === $this) {
                $userTrick->setTrickAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getUserComments(): Collection
    {
        return $this->user_comments;
    }

    public function addUserComment(Comment $userComment): self
    {
        if (!$this->user_comments->contains($userComment)) {
            $this->user_comments[] = $userComment;
            $userComment->setCommentAuthor($this);
        }

        return $this;
    }

    public function removeUserComment(Comment $userComment): self
    {
        if ($this->user_comments->removeElement($userComment)) {
            // set the owning side to null (unless already changed)
            if ($userComment->getCommentAuthor() === $this) {
                $userComment->setCommentAuthor(null);
            }
        }

        return $this;
    }
}

templates/trick/comment_thread.html.twig
{% if index == 1 or index == 2 %}
    {% set start_index = 5 %}
    {% set end_index = 5 %}
{% else %}
    {% set start_index = (index - 1) * 5 %}
    {% set end_index = 5 %}
{% endif %}
{% for comment in comments|reverse|slice(start_index, end_index) %}
    <div class="trick-comment d-flex justify-content-center">
        <a name="comment_{{ comment.id }}"></a>
        <div class="col-md-1 picture-comment-container">
            <img src="/assets/images/users/{{ comment.commentAuthor.userAvatar }}" class="user-avatar"
                alt="{{ comment.commentAuthor.userAvatar }}" />
        </div>
        <div class="col-md-11 comment-container">
            <h4>
                <strong>{{ comment.commentAuthor.username }}</strong> a commenté le
                {# it's not mandatory to set the timezone in localizeddate(). This is done to
                avoid errors when the 'intl' PHP extension is not available and the application
                is forced to use the limited "intl polyfill", which only supports UTC and GMT #}
                <strong>{{ comment.commentCreationDate|date('d/m/Y à H:i:h') }}</strong>
            </h4>
            <div>
                {{ comment.commentContent }}
            </div>
        </div>
    </div>
    {% else %}
    <div class="trick-comment text-center">
        <p>Fin des commentaires !
            Pour en ajouter <a href="{{ path('app_register') }}" title="Page de création de compte" class="fw-bold">créer un
                compte </a> ou <a href="{{ path('security_login') }}" title="Page de connexion"
                class="fw-bold">connectez-vous</a> !</p>
    </div>
{% endfor %}

templates/trick/index.html.twig
{% for trick in paginator.results %}
    <div class="col">
        <div class="card">
            <div class="crop">
                <a href="{{ path('trick_detail', {trick_slug: trick.trickSlug}) }}"  title="Cliquer pour consulter la figure {{ trick.trickName }}">
                    <img src="{{ uploads_base_url ~ '/images/' ~  trick.TrickThumbnail }}" class="card-img-top" alt="">
                </a>
            </div>
            <div class="card-body">
                <h5 class="card-title text-center"><a href="{{ path('trick_detail', {trick_slug: trick.trickSlug}) }}"
                        title="Cliquer pour consulter la figure {{ trick.trickName }}">{{
                        trick.trickName|u.truncate(20, '...') }}</a></h5>
                {% if is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_ADMIN') and trick.TrickAuthorId == app.user.id %}
                    {{ include('trick/_delete_trick_confirmation.html.twig') }}
                    <div class="d-flex justify-content-end edit-btn">
                        <a href="{{ path('admin_trick_edit', {trick_slug: trick.trickSlug}) }}" title="Éditer la figure" class="d-block pr-2"><i class="fas fa-edit"></i></a>
                        <form action="{{ url('admin_trick_delete', {trick_slug: trick.TrickSlug}) }}" method="post" data-confirmation="true" id="delete-form">
                            <input type="hidden" name="token" value="{{ csrf_token('delete') }}" />
                            <button type="submit" class="btn btn-lg btn-block btn-danger" style="font-size: .7em">
                                <i class="fa fa-trash" aria-hidden="true"></i>
                            </button>
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% else %}
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        <div class="well w-100 text-center fw-bold"><p>Aucune autre figure trouvé !</p></div>
    {% else %}
        <div class="well w-100 text-center"><p>Aucune autre figure trouvé. Pour en ajouter <a href="{{ path('app_register') }}" title="Page de création de compte" class="fw-bold">créer un compte </a> ou <a href="{{ path('security_login') }}" title="Page de connexion" class="fw-bold">connectez-vous</a> !</p></div>
    {% endif %}
{% endfor %}

templates/trick/trick_show.html.twig
{% extends 'base.html.twig' %}
{% import 'macros/alertes.html.twig' as utils %}

{% block title %}Figures | {{ title_page }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdn.plyr.io/3.6.12/plyr.css" />
    <link href="/dist/css/trick_details.css" rel="stylesheet">
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="https://cdn.plyr.io/3.6.12/plyr.js"></script>
    <script>
        const trick_slug = "{{ trick.trickSlug }}";
        $(window).on('load', function () {
            const players = Array.from(document.querySelectorAll('.js-player')).map((p) => new Plyr(p));
        });
    </script>
    <script src="/dist/js/trick_details.js"></script>
{% endblock %}

{% block body_id 'trick_details' %}

{% block hero %}
    {{ include('_hero_section.html.twig', { show: false, title: null }) }}
{% endblock %}

{% block flash_message %}{% endblock %}

{% block main %}
    <!-- ======= Trick Detail ======= -->
    <main id="main">
        {{ no_script|raw }}

        <section class="container detail-box mb-5">
                <header class="row detail-header" style="background-image: linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7)), url({{ uploads_base_url ~ '/images/' ~  trick.TrickThumbnail }})">
                    {% if is_granted('IS_AUTHENTICATED_FULLY') and is_granted('ROLE_ADMIN') and trick.TrickAuthorId == app.user.id %}
                        {{ include('trick/_delete_trick_confirmation.html.twig') }}
                        <div class="d-flex justify-content-end edit-btn">
                            <a href="{{ path('admin_trick_edit', {trick_slug: trick.trickSlug}) }}" title="Éditer la figure" class="d-block pr-2"><i class="fas fa-edit"></i></a>
                            <form action="{{ url('admin_trick_delete', {trick_slug: trick.TrickSlug}) }}" method="post" data-confirmation="true" id="delete-form">
                                <input type="hidden" name="token" value="{{ csrf_token('delete') }}" />
                                <button type="submit" class="btn btn-lg btn-block btn-danger" style="font-size: .7em">
                                    <i class="fa fa-trash" aria-hidden="true"></i>
                                </button>
                            </form>
                        </div>
                    {% endif %}
                    
                    <h1 class="text-uppercase text-center">{{ trick.TrickName }}</span>
                </header>
                {% for label, messages in app.flashes(['success', 'error', 'warning', 'info']) %}
                    {% for message in messages %}
                        {{ utils.alert(message, label) }}
                    {% endfor %}
                {% endfor %}
                <aside class="container trick-attachment-section">
                    <div class="row row-cols-1 mt-5 row-cols-md-4 g-4 trick-attachment hide-content hidden-container">
                        {% for reference in trick.trickAttachments %}
                            {% if reference.TaType == 'image'%}
                                <div class="card text-white">
                                    <figure class="hover-img">
                                        <img src="{{ uploads_base_url }}/{{ reference.filePath }}" alt="Card image">
                                        <figcaption>
                                            {{ reference.TaOriginalFilename|u.truncate(15, '...') }}
                                        </figcaption>
                                    </figure>
                                </div>
                            {% endif %}
                        {% endfor %}

                        {% for reference in trick.trickAttachments %}
                            {% if reference.TaType == 'video'%}
                                <div class="card text-white w-100">
                                    <video class="js-player" playsinline controls>
                                        <source src="{{ uploads_base_url }}/{{ reference.filePath }}" type="{{ reference.TaMimeType }}" />
                                    </video>
                                </div>
                            {% endif %}
                        {% endfor %}

                        {% if trick.trickAttachments is empty %}
                            <script>
                                $(window).on('load', function () {
                                    $('.trick-attachment-section').css('display', 'none');
                                })
                            </script>
                        {% endif %}
                    </div>

                    <button class="btn btn-outline-dark show-more" data-status="more"><i class="fas fa-chevron-down"></i></button>
                </aside>
                
                <article class="row trick-description-section mt-30">
                    <!-- <header>
                        <h1>{{ trick.TrickName }}</h1>
                    </header> -->

                    <main>
                        <section class="post-description">
                            <p>{{ trick.TrickDescription|markdown_to_html }}</p>
                        </section>

                        <section class="post-metadata mt-5">
                            <span class="metadata"><i class="fa fa-calendar"></i> {{ trick.trickCreationDate|date('d/m/Y à H:i:h') }}</span>
                            {% if trick.TrickUpdateDate is defined and trick.TrickUpdateDate is not null %}
                                <span class="metadata"><i class="fas fa-pen"></i> {{ trick.TrickUpdateDate|date('d/m/Y à H:i:h') }}</span>
                            {% endif %}
                            <span class="metadata"><i class="fa fa-user"></i> {{ trick.trickAuthor.username }}</span>
                            <span class="metadata"><i class="fas fa-tags"></i> {{ trick.trickGroup.groupName }}</span>
                        </section>
                    </main>
                </article>

                <section class="row comment-section d-flex justify-content-center">
                    <div id="post-add-comment" class="container well">
                            <hr />
                                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                                    {{ render(controller('App\\Controller\\TrickController::commentForm', {'id': trick.id})) }}
                                {% else %}
                                    <p>
                                        <a class="btn btn-dark" href="{{ path('security_login', {'redirect_to': app.request.pathInfo}) }}">
                                            <i class="fas fa-sign-in-alt"></i>  Connectez-vous
                                        </a>
                                        pour publier un commentaire
                                    </p>
                                {% endif %}
                            <hr />
                    </div>

                    <div>
                        <h3>
                            <i class="fa fa-comments" aria-hidden="true"></i> Commentaires ({{ trick.trickComments|length }}) :
                        </h3>
                    </div>

                    <div>
                        {% for comment in comments|reverse|slice(0, 5) %}
                            <div class="trick-comment d-flex justify-content-center">
                                <a name="comment_{{ comment.id }}"></a>
                                <div class="col-md-1 picture-comment-container">
                                    <img src="/assets/images/users/{{ comment.commentAuthor.userAvatar }}" class="user-avatar" alt="{{ comment.commentAuthor.userAvatar }}" />
                                </div>
                                <div class="col-md-11 comment-container">
                                    <h4>
                                        <strong>{{ comment.commentAuthor.username }}</strong> a commenté le
                                        {# it's not mandatory to set the timezone in localizeddate(). This is done to
                                        avoid errors when the 'intl' PHP extension is not available and the application
                                        is forced to use the limited "intl polyfill", which only supports UTC and GMT #}
                                        <strong>{{ comment.commentCreationDate|date('d/m/Y à H:i:h') }}</strong>
                                    </h4>
                                    <div>
                                        {{ comment.commentContent }}
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                                <div class="trick-comment">
                                    <p class="text-center fw-bold">Aucun commentaire.</p>
                                </div>
                            {% else %}
                                <div class="trick-comment">
                                    <p class="text-center">Aucun commentaire.  
                                    Pour en ajouter <a href="{{ path('app_register') }}" title="Page de création de compte" class="fw-bold">créer un compte </a> ou <a href="{{ path('security_login') }}" title="Page de connexion" class="fw-bold">connectez-vous</a> !</p>
                                </div>
                            {% endif %}
                            <script>
                                $(window).on('load', function () {
                                    $('.comment-btn').css('display', 'none');
                                })
                            </script>
                        {% endfor %}
                    </div>
                    <button type="button" class="w-75  btn btn-outline-dark mt-5 mb-5 load-more-btn comment-btn">
                        <span class="spinner-grow spinner-grow-lg" role="status" aria-hidden="true"></span>
                        <span class="button-text">Charger plus de commentaires</span>
                    </button>
                </section>
        </section>
    </main>
{% endblock %}